[package]
name = "hyprland-mcp"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
rmcp = "0.16"
schemars = "1.2.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.49.0", features = ["io-std", "net", "rt-multi-thread"] }
